'use client';

import { useState } from 'react';
import { api } from '@/lib/api';

/**
 * "Öğren" — takes a story into the learning queue, from the action row.
 *
 * It used to be a block halfway down the article explaining itself in two
 * sentences. It is an icon now, beside save, wearing the same spark the Öğren tab
 * wears in the nav — because that is where the story goes, and a reader who knows
 * the tab needs no sentence to know the button.
 *
 * Nothing is generated by this press. It writes a queue row; the lesson is
 * produced from the foot of the story, deliberately and at the cost of a model
 * call.
 *
 * Controlled, like the verdict buttons beside it: the row is drawn twice on a
 * story page and two copies keeping their own idea of whether the story is taken
 * would disagree the moment either is used.
 */
export function LearnButton({
  storyId,
  briefId,
  onQueued,
}: {
  storyId: string;
  /** The unfinished lesson this story is already part of, if any. */
  briefId: string | null;
  onQueued: (briefId: string) => void;
}) {
  const [busy, setBusy] = useState(false);
  const [failed, setFailed] = useState(false);

  const taken = briefId !== null;

  const queue = async () => {
    if (taken || busy) return;

    setBusy(true);
    setFailed(false);

    try {
      // Idempotent server-side, so a double press returns the same brief rather
      // than a second one for the same story.
      const brief = await api.learning.briefs.queueStory(storyId);
      onQueued(brief.id);
    } catch {
      setFailed(true);
    } finally {
      setBusy(false);
    }
  };

  const label = failed
    ? 'Eklenemedi — tekrar dene'
    : taken
      ? 'Öğrenmeye alındı'
      : 'Öğrenmeye al';

  return (
    <button
      type="button"
      onClick={queue}
      disabled={taken || busy}
      aria-pressed={taken}
      aria-label={label}
      title={label}
      className={`tap-44 rounded-lg p-2 transition hover:bg-ink-100 disabled:hover:bg-transparent
                  dark:hover:bg-ink-800 dark:disabled:hover:bg-transparent ${
                    failed
                      ? 'text-signal-hype'
                      : taken
                        ? 'text-focus-600 dark:text-focus-400'
                        : 'text-ink-500 dark:text-ink-400'
                  } ${busy ? 'opacity-60' : ''}`}
    >
      {/* The nav's Öğren glyph, to the pixel: the button says where the story is
          going, and it can only say it by looking like the place. */}
      <svg
        className="h-5 w-5"
        viewBox="0 0 24 24"
        fill={taken ? 'currentColor' : 'none'}
        stroke="currentColor"
        strokeWidth={1.8}
        aria-hidden="true"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          d="M12 3l2.1 5.4L19.5 10l-5.4 2.1L12 17.5 9.9 12.1 4.5 10l5.4-1.6z"
        />
      </svg>
    </button>
  );
}
