'use client';

import Link from 'next/link';
import { useState } from 'react';
import { api, describeError } from '@/lib/api';
import { trUpper } from '@/lib/format';
import type { LearningBrief } from '@/lib/types';

/**
 * "Bunu öğren" — sends a story to the learning queue.
 *
 * A block rather than another icon in the top bar. That row already carries
 * feedback, share and save, and on a phone a fifth 44px target does not fit
 * without shrinking the others below the tap minimum. It also belongs here in
 * the reading order: deciding to study something is a decision you make after
 * reading it, not before.
 *
 * Nothing is generated by this press. It writes a queue row; the prompt is a
 * separate, deliberate press in the Öğren tab.
 */
export function LearnButton({ storyId }: { storyId: string }) {
  const [brief, setBrief] = useState<LearningBrief | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const queue = async () => {
    setBusy(true);
    setError(null);

    try {
      // Idempotent server-side, so a second press returns the same brief rather
      // than a duplicate.
      setBrief(await api.learning.briefs.queueStory(storyId));
    } catch (caught) {
      setError(describeError(caught, 'Öğrenme kuyruğuna eklenemedi.'));
    } finally {
      setBusy(false);
    }
  };

  return (
    <section className="card p-4 sm:p-5">
      <p className="font-mono text-[11px] tracking-[0.13em] text-focus-600 dark:text-focus-400">
        {trUpper('Bu konuyu çalış')}
      </p>

      <p className="mt-1.5 font-serif text-sm leading-relaxed text-ink-600 dark:text-ink-300">
        Bu haberin kaynakları, alıntıları ve kanıt kaydından Focus Mentor için bir ders promtu
        çıkarılır. Promtu Öğren sekmesinde üretirsin.
      </p>

      {error && <p className="mt-2 text-xs text-signal-hype">{error}</p>}

      <div className="mt-3">
        {brief ? (
          <Link href={`/learning/brief/${brief.id}`} className="btn-ghost w-full">
            ✓ Öğren sekmesine eklendi — aç
          </Link>
        ) : (
          <button type="button" onClick={queue} disabled={busy} className="btn-primary w-full">
            {busy ? 'Ekleniyor…' : 'Öğrenmeye al'}
          </button>
        )}
      </div>
    </section>
  );
}
