namespace FocusAI.Domain.Common;

/// <summary>
/// Storage limits for the free-text fields that come from a language model.
/// </summary>
/// <remarks>
/// These are declared once and consumed by both the EF configuration and the
/// enrichment handler that writes them. Duplicating the numbers is how a model
/// that ignores its length instruction turns into a 500: the column says 600,
/// the handler assumes the prompt was obeyed, and Postgres rejects the insert.
/// Nothing generated by a model is trusted to be within bounds.
/// </remarks>
public static class FieldLimits
{
    public const int StoryTitle = 500;

    public const int StoryDek = 600;

    public const int Summary = 4000;

    public const int SummarySection = 2000;

    public const int ExtendedSummary = 12_000;

    public const int KeyPoint = 400;

    /// <summary>Cards show three to five bullets; more is noise, not value.</summary>
    public const int KeyPointCount = 6;

    public const int AnalysisSection = 2000;

    public const int StackNote = 1000;

    public const int ProviderName = 50;

    public const int ModelName = 100;

    /// <summary>
    /// Truncates on a word boundary and marks the cut, so a clipped sentence
    /// reads as deliberate rather than as corrupted data.
    /// </summary>
    public static string? Cap(string? value, int maxLength)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return value;
        }

        var trimmed = value.Trim();
        if (trimmed.Length <= maxLength)
        {
            return trimmed;
        }

        // Reserve one character for the ellipsis.
        var slice = trimmed[..(maxLength - 1)];
        var lastSpace = slice.LastIndexOf(' ');

        // Only honour the word boundary when it is not absurdly early, otherwise
        // a single very long token would collapse the whole field.
        if (lastSpace > maxLength / 2)
        {
            slice = slice[..lastSpace];
        }

        return slice.TrimEnd(' ', ',', ';', ':', '-') + "…";
    }
}
